<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <RootNamespace>Project_auto_push_to_gitlab</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <FileVersion>0.0.1.0624</FileVersion>
    <AssemblyVersion>0.0.0.114</AssemblyVersion>
  </PropertyGroup>

</Project>